### PR TITLE
Adding a suite with CodeQL security queries only without OE specific

### PR DESCRIPTION
**Pull request by mrragava**
Signed-off-by: mrragava <mrragava@gmail.com>

### CODE REVIEW

**Review by rs-- — APPROVED** [review]

**Comment by ghost** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/openenclave/openenclave-security/pull/6#" title="Author self-approved">mrragava</a>*, *<a href="https://github.com/openenclave/openenclave-security/pull/6#pullrequestreview-605692280" title="Approved">rs--</a>*

The full list of commands accepted by this bot can be found [here](?repo=openenclave%2Fopenenclave-security).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/openenclave/openenclave-security/blob/main/OWNERS)~~ [mrragava]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by rs--** [comment]
\lgtm

**Comment by ghost** [comment]
@rs--: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/openenclave/openenclave-security/pull/6#issuecomment-791799974):

>/lgtm
>
>/approved


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
