### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BRMcLaren**

### CODE REVIEW

**Comment by ghost** [comment]
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/openenclave/openenclave-security/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [7da28bd](https://github.com/openenclave/openenclave-security/commits/7da28bdc16f12933ac90612f0b7a7b9f0d0d56ff) Update README.md

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ghost** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/openenclave/openenclave-security/pull/1#" title="Author self-approved">BRMcLaren</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mrragava**
You can assign the PR to them by writing `/assign @mrragava` in a comment when ready.

The full list of commands accepted by this bot can be found [here](?repo=openenclave%2Fopenenclave-security).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/openenclave/openenclave-security/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by BRMcLaren** [comment]
@mrragava You should be unblocked now for dco and CI hook up. Let's not merge this PR and close it once you have confirmed there is nothing else to be done :)

**Comment by mrragava** [comment]
Thanks Brett!

**Comment by BRMcLaren** [comment]
confirmed offline.

/close

**Pull request closed without merging**
